require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/years", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Year. As you add validations to Year, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Year.create! valid_attributes
      get years_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      year = Year.create! valid_attributes
      get year_url(year)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_year_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      year = Year.create! valid_attributes
      get edit_year_url(year)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Year" do
        expect {
          post years_url, params: { year: valid_attributes }
        }.to change(Year, :count).by(1)
      end

      it "redirects to the created year" do
        post years_url, params: { year: valid_attributes }
        expect(response).to redirect_to(year_url(Year.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Year" do
        expect {
          post years_url, params: { year: invalid_attributes }
        }.to change(Year, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post years_url, params: { year: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested year" do
        year = Year.create! valid_attributes
        patch year_url(year), params: { year: new_attributes }
        year.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the year" do
        year = Year.create! valid_attributes
        patch year_url(year), params: { year: new_attributes }
        year.reload
        expect(response).to redirect_to(year_url(year))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        year = Year.create! valid_attributes
        patch year_url(year), params: { year: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested year" do
      year = Year.create! valid_attributes
      expect {
        delete year_url(year)
      }.to change(Year, :count).by(-1)
    end

    it "redirects to the years list" do
      year = Year.create! valid_attributes
      delete year_url(year)
      expect(response).to redirect_to(years_url)
    end
  end
end
